### ISSUE TITLE
Upload built jars after release

### ISSUE THREAD

**Issue by nicocti** [geotrellis/geotrellis-gdal#62]
Hey,

If it's easy for you, it would be cool to upload a jar either on github or oss.jfrog.org after a release.

I cannot find the 0.18.5 build on oss.jfrog.org (mayby I'm not using it properly) and I'm not very good at building via sbt...

**Comment by pomadchin** [comment]
Hey, It's here: https://bintray.com/azavea/geotrellis/geotrellis-gdal

Also we probably will drop this repository, since we are not satisfied by the original GDAL JNI bindings performance. 

We develop a new API and a new JNI bindings: 

* https://github.com/geotrellis/geotrellis-contrib/tree/master/gdal
* https://github.com/geotrellis/gdal-warp-bindings

**Comment by nicocti** [comment]
Oh ! Thanks a lot for the info, I'm gonna have a look.
